#!/bin/bash

# THIS SETUP FILE MUST BE RUN FROM THIS FOLDER (_hooks)!!
# In order to make the file executable, run 
# chmod +x hooks_setup
# And run the file with:
# ./hooks_setup

# pre-commit hook requires multiple linters, follow these steps to install them:

# Upgrading pip to latest version 
# pip install --upgrade pip

# Installing all the linters
# pip install pylint flake8 ruff black pycodestyle pydocstyle mypy django-stubs

# The following commands will create symbolic links for both hooks
ln -s -f ../../_hooks/commit-msg ../.git/hooks/commit-msg
ln -s -f ../../_hooks/pre-commit ../.git/hooks/pre-commit

