# Generated by Django 4.2.2 on 2023-08-09 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=100)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('event_time', models.TimeField(default=django.utils.timezone.now)),
                ('product_type', models.CharField(max_length=100)),
                ('pickup_time', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=1000)),
                ('delivery_time', models.CharField(max_length=100)),
                ('delivery_pincode', models.IntegerField()),
                ('pickup_pincode', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(max_length=100, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='userAuth.seller')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to='userAuth.buyer')),
            ],
        ),
    ]
