# Generated by Django 4.2.2 on 2023-08-17 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("buyer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="delivery_date",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="pickup_date",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
