#!/bin/sh

#########################################################################################
#                                                                                       #
#   In order use these commit hooks place them in the BASE_DIR/.git/hooks/<your-hook>   #
#                                                                                       #  
#########################################################################################

run_python_linters() {
    echo "Running Python linters..."
    
    # linters can be installed by command: pip install <linter_name>
    
    flake8 .

    # black can also be used, however, it offers fewer comprehensive linting capabilities compared to flake8.
    # black --check --diff --color .

    exit_code=$?

    # If the linters fail, prevent the commit
    if [ $exit_code -ne 0 ]; then
        echo "Python linters failed, Commit aborted."
        echo "Please reformat your code."
        exit 1
    fi
}

run_test(){

    echo -e "\nRunning Django test suite before committing..."

    # Running the Django test suite
    python manage.py test 

    TEST_EXIT_CODE=$?

    if [ $TEST_EXIT_CODE -ne 0 ]; then
        echo "Django tests failed. Please fix the issues before committing."
        exit 1
    fi

    echo "Django tests passed." 
    exit 0
}

run_python_linters
run_test
